In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

df = pd.read_json('solution_table.json')
print('done')

done

In [127]:
print (df.head(3))
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(df.dtypes)
# df.to_csv('test.csv',sep='\t', encoding='utf-8')
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df.head(3))
print(df.shape[0])
count_nan = df['beg_fov'].isnull().sum()
print ('Count of NaN: ' + str(count_nan))

   __type__       solution_id solver       jdt_ref  \
0  Solution  20161105_072006A  pylig  2.457698e+06
1  Solution  20161105_073705A  pylig  2.457698e+06
2  Solution  20161105_073915A  pylig  2.457698e+06

                            utc_ref  shower_no shower_code   solar_lon  \
0  2016-11-05T07:20:06.394489+00:00         -1         ...  223.081280
1  2016-11-05T07:37:05.105721+00:00         -1         ...  223.093105
2  2016-11-05T07:39:15.512094+00:00         -1         ...  223.094618

   local_sidereal_time      ra_geo  ...  height_ch  cos_elevation_norot  \
0            73.879490   25.870975  ...  16.263025             0.545926
1            78.091118   95.334449  ...   5.234176             0.820769
2            78.780189  128.599210  ...  13.849401             0.811326

   elevation_norot_rad  obs_ci_lower  obs_ci_upper      mean  obs_ci_lower1  \
0             0.993302           NaN           NaN       NaN            NaN
1             0.608040     -0.426931     22.988372  11.28072       5.340497
2             0.624380           NaN           NaN       NaN            NaN

   obs_ci_upper1  obs_ci_lower3  obs_ci_upper3
0            NaN            NaN            NaN
1      17.220944      -6.447148      29.008588
2            NaN            NaN            NaN

[3 rows x 98 columns]
__type__                object
solution_id             object
solver                  object
jdt_ref                float64
utc_ref                 object
shower_no                int64
shower_code             object
solar_lon              float64
local_sidereal_time    float64
ra_geo                 float64
dec_geo                float64
lam_geo                float64
bet_geo                float64
vel_geo                float64
lam_hel                float64
bet_hel                float64
vel_hel                float64
a                      float64
e                      float64
i                      float64
omega                  float64
asc_node               float64
pi                     float64
q                      float64
true_anomaly           float64
mean_anomaly           float64
Q                      float64
n                      float64
T                      float64
Tj                     float64
ra_app                 float64
dec_app                float64
azimuth_norot          float64
elevation_norot        float64
vel_init_norot         float64
vel_avg_norot          float64
begin_latitude         float64
begin_longitude        float64
begin_height           float64
end_latitude           float64
end_longitude          float64
end_height             float64
duration               float64
convergence_angle      float64
median_fit_err         float64
station_list            object
ra_geo_err             float64
dec_geo_err            float64
lam_geo_err            float64
bet_geo_err            float64
vel_geo_err            float64
lam_hel_err            float64
bet_hel_err            float64
vel_hel_err            float64
a_err                  float64
e_err                  float64
i_err                  float64
omega_err              float64
asc_node_err           float64
pi_err                 float64
q_err                  float64
true_anomaly_err       float64
mean_anomaly_err       float64
Q_err                  float64
n_err                  float64
T_err                  float64
Tj_err                 float64
ra_app_err             float64
dec_app_err            float64
azimuth_norot_err      float64
elevation_norot_err    float64
vel_init_norot_err     float64
vel_avg_norot_err      float64
begin_latitude_err     float64
begin_longitude_err    float64
begin_height_err       float64
end_latitude_err       float64
end_longitude_err      float64
end_height_err         float64
beg_fov                   bool
end_fov                   bool
radiant_err            float64
radiated_energy        float64
mass                   float64
peak_abs_mag           float64
peak_height            float64
F                      float64
num_stations             int64
height_ch              float64
cos_elevation_norot    float64
elevation_norot_rad    float64
obs_ci_lower           float64
obs_ci_upper           float64
mean                   float64
obs_ci_lower1          float64
obs_ci_upper1          float64
obs_ci_lower3          float64
obs_ci_upper3          float64
dtype: object

,__type__,solution_id,solver,jdt_ref,utc_ref,shower_no,shower_code,solar_lon,local_sidereal_time,ra_geo,dec_geo,lam_geo,bet_geo,vel_geo,lam_hel,bet_hel,vel_hel,a,e,i,omega,asc_node,pi,q,true_anomaly,mean_anomaly,Q,n,T,Tj,ra_app,dec_app,azimuth_norot,elevation_norot,vel_init_norot,vel_avg_norot,begin_latitude,begin_longitude,begin_height,end_latitude,end_longitude,end_height,duration,convergence_angle,median_fit_err,station_list,ra_geo_err,dec_geo_err,lam_geo_err,bet_geo_err,vel_geo_err,lam_hel_err,bet_hel_err,vel_hel_err,a_err,e_err,i_err,omega_err,asc_node_err,pi_err,q_err,true_anomaly_err,mean_anomaly_err,Q_err,n_err,T_err,Tj_err,ra_app_err,dec_app_err,azimuth_norot_err,elevation_norot_err,vel_init_norot_err,vel_avg_norot_err,begin_latitude_err,begin_longitude_err,begin_height_err,end_latitude_err,end_longitude_err,end_height_err,beg_fov,end_fov,radiant_err,radiated_energy,mass,peak_abs_mag,peak_height,F,num_stations,height_ch,cos_elevation_norot,elevation_norot_rad,obs_ci_lower,obs_ci_upper,mean,obs_ci_lower1,obs_ci_upper1,obs_ci_lower3,obs_ci_upper3
0,Solution,20161105_072006A,pylig,2.457698e+06,2016-11-05T07:20:06.394489+00:00,-1,...,223.081280,73.879490,25.870975,41.105498,39.714383,28.192030,28.309854,351.896157,18.300147,42.594522,-35.889932,1.017928,22.999066,252.295854,223.080408,115.376262,0.643424,287.706522,NaN,-72.423288,0.004584,NaN,0.774555,28.282275,41.913696,283.131473,56.912025,30.223888,27.878597,43.644811,-81.102568,104.559933,43.623357,-80.976459,88.296908,0.659000,11.749460,0.002902,"[02F, 01F]",0.051473,0.071691,0.072059,0.051094,0.093099,0.103385,0.074147,0.043831,3.038048,0.002675,0.119922,0.047182,0.000012,0.047193,0.000818,0.047192,NaN,6.076888,0.001215,NaN,0.022747,0.042241,0.065750,0.098078,0.049584,0.087074,0.058344,0.000124,0.000108,0.040069,0.000118,0.000066,0.031611,True,False,0.081500,13.202340,4.853343e-06,3.440756,89.581930,0.920985,2,16.263025,0.545926,0.993302,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Solution,20161105_073705A,pylig,2.457698e+06,2016-11-05T07:37:05.105721+00:00,-1,...,223.093105,78.091118,95.334449,-12.984042,96.454300,-36.302299,20.684091,345.022966,-31.943232,23.145581,0.707515,0.574465,36.301966,155.291525,43.095817,198.387342,0.301072,204.706876,249.241369,1.113957,1.656156,0.595119,7.842152,95.365573,-9.317753,159.082696,34.838140,23.576768,24.420382,43.560143,-81.147294,91.153844,43.622565,-81.180142,85.919668,0.419000,25.998125,0.002618,"[02F, 01F]",0.020992,0.124462,0.027545,0.124158,0.034860,0.114661,0.082456,0.025090,0.000653,0.001642,0.090856,0.073954,0.000004,0.073957,0.001421,0.073957,0.108653,0.000429,0.002299,0.000823,0.006249,0.019496,0.114051,0.040769,0.110689,0.030709,0.009051,0.000045,0.000024,0.011495,0.000047,0.000022,0.008193,True,True,0.126133,8.692784,4.164721e-06,3.036135,91.153844,0.000000,2,5.234176,0.820769,0.608040,-0.426931,22.988372,11.28072,5.340497,17.220944,-6.447148,29.008588
2,Solution,20161105_073915A,pylig,2.457698e+06,2016-11-05T07:39:15.512094+00:00,-1,...,223.094618,78.780189,128.599210,10.316363,128.317868,-8.135898,59.837313,122.593565,-16.027685,30.670493,1.045026,0.182328,163.713751,84.010585,43.092839,127.103424,0.854489,275.986057,296.360640,1.235563,0.922600,1.068296,4.134199,128.697239,10.571857,112.023080,35.774331,61.113851,61.274856,43.657663,-81.003168,114.260810,43.721448,-81.221295,100.411408,0.386805,15.789271,0.007873,"[01F, 02F]",0.100846,0.207255,0.148692,0.176684,0.171292,0.276084,0.373658,0.161877,0.012913,0.007678,0.365456,2.991301,0.000069,2.991323,0.005840,2.991280,3.179342,0.022561,0.016166,0.020028,0.063973,0.098327,0.203471,0.089755,0.213014,0.168151,0.087042,0.000153,0.000082,0.057342,0.000235,0.000223,0.050704,True,False,0.229765,8.658595,6.588929e-07,3.474886,104.637621,0.694845,2,13.849401,0.811326,0.624380,NaN,NaN,NaN,NaN,NaN,NaN,NaN

81018
Count of NaN: 0

In [118]:
import numpy as np
df['elevation_norot_rad'] = np.deg2rad(df['elevation_norot'])
df['cos_elevation_norot'] = np.cos(df['elevation_norot_rad'])
df['height_ch'] = df['begin_height'] - df['end_height']
df1 = df[(df['beg_fov'] == True) & (df['end_fov'] == True) & (df['height_ch'] > 0) ]

In [128]:
df2 = df1[['vel_avg_norot','cos_elevation_norot','peak_abs_mag','height_ch']].dropna()
X = df2[['vel_avg_norot','cos_elevation_norot','peak_abs_mag']]
Y = df2['height_ch']
X = sm.add_constant(X)   
model= sm.OLS(Y,X).fit()   
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              height_ch   R-squared:                       0.222
Model:                            OLS   Adj. R-squared:                  0.222
Method:                 Least Squares   F-statistic:                     5546.
Date:                Tue, 12 Jul 2022   Prob (F-statistic):               0.00
Time:                        12:32:13   Log-Likelihood:            -1.8670e+05
No. Observations:               58232   AIC:                         3.734e+05
Df Residuals:                   58228   BIC:                         3.734e+05
Df Model:                           3
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                  22.6791      0.151    149.876      0.000      22.383      22.976
vel_avg_norot           0.0457      0.001     45.975      0.000       0.044       0.048
cos_elevation_norot    -7.9932      0.110    -72.870      0.000      -8.208      -7.778
peak_abs_mag           -1.9613      0.024    -83.149      0.000      -2.008      -1.915
==============================================================================
Omnibus:                    66395.848   Durbin-Watson:                   1.848
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         12694500.145
Skew:                           5.726   Prob(JB):                         0.00
Kurtosis:                      74.420   Cond. No.                         294.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [129]:
predictions2 = model.get_prediction(X).summary_frame(alpha=0.05)
df['obs_ci_lower'] = predictions2['obs_ci_lower']
df['obs_ci_upper'] = predictions2['obs_ci_upper']
df['mean'] = predictions2['mean']
predictions2

,mean,mean_se,mean_ci_lower,mean_ci_upper,obs_ci_lower,obs_ci_upper
1,11.280720,0.057985,11.167069,11.394372,-0.426931,22.988372
3,10.273270,0.025464,10.223361,10.323180,-1.433936,21.980477
4,7.440248,0.037850,7.366061,7.514435,-4.267087,19.147583
5,12.085495,0.041111,12.004916,12.166073,0.378117,23.792872
6,11.594804,0.056633,11.483804,11.705805,-0.112822,23.302431
...,...,...,...,...,...,...
81011,5.457314,0.041792,5.375402,5.539227,-6.250072,17.164701
81012,10.887470,0.048240,10.792920,10.982020,-0.820012,22.594952
81013,9.469885,0.032164,9.406843,9.532927,-2.237385,21.177155
81016,14.268166,0.068920,14.133082,14.403250,2.560286,25.976045
81017,14.372161,0.044895,14.284167,14.460155,2.664730,26.079592

In [130]:
predictions1 = model.get_prediction(X).summary_frame(alpha=0.32)
df['obs_ci_lower1'] = predictions1['obs_ci_lower']
df['obs_ci_upper1'] = predictions1['obs_ci_upper']
predictions1

,mean,mean_se,mean_ci_lower,mean_ci_upper,obs_ci_lower,obs_ci_upper
1,11.280720,0.057985,11.223056,11.338385,5.340497,17.220944
3,10.273270,0.025464,10.247947,10.298594,4.333273,16.213268
4,7.440248,0.037850,7.402607,7.477889,1.500185,13.380311
5,12.085495,0.041111,12.044611,12.126379,6.145411,18.025579
6,11.594804,0.056633,11.538485,11.651124,5.654594,17.535015
...,...,...,...,...,...,...
81011,5.457314,0.041792,5.415754,5.498875,-0.482775,11.397403
81012,10.887470,0.048240,10.839497,10.935443,4.947333,16.827607
81013,9.469885,0.032164,9.437899,9.501871,3.529856,15.409915
81016,14.268166,0.068920,14.199627,14.336705,8.327827,20.208505
81017,14.372161,0.044895,14.327515,14.416807,8.432050,20.312272

In [131]:
predictions3 = model.get_prediction(X).summary_frame(alpha=0.003)
df['obs_ci_lower3'] = predictions3['obs_ci_lower']
df['obs_ci_upper3'] = predictions3['obs_ci_upper']
predictions3

,mean,mean_se,mean_ci_lower,mean_ci_upper,obs_ci_lower,obs_ci_upper
1,11.280720,0.057985,11.108628,11.452813,-6.447148,29.008588
3,10.273270,0.025464,10.197696,10.348844,-7.453923,28.000464
4,7.440248,0.037850,7.327914,7.552582,-10.287141,25.167637
5,12.085495,0.041111,11.963482,12.207508,-5.641958,29.812947
6,11.594804,0.056633,11.426726,11.762883,-6.133025,29.322634
...,...,...,...,...,...,...
81011,5.457314,0.041792,5.333282,5.581347,-12.270152,23.184781
81012,10.887470,0.048240,10.744301,11.030639,-6.840141,28.615081
81013,9.469885,0.032164,9.374427,9.565344,-8.257405,27.197175
81016,14.268166,0.068920,14.063620,14.472712,-3.460047,31.996379
81017,14.372161,0.044895,14.238920,14.505402,-3.355372,32.099694

In [132]:
import os
df1 = df[(df['beg_fov'] == True) & (df['end_fov'] == True) & (df['height_ch'] > 0)]
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df1.head(3))

,__type__,solution_id,solver,jdt_ref,utc_ref,shower_no,shower_code,solar_lon,local_sidereal_time,ra_geo,dec_geo,lam_geo,bet_geo,vel_geo,lam_hel,bet_hel,vel_hel,a,e,i,omega,asc_node,pi,q,true_anomaly,mean_anomaly,Q,n,T,Tj,ra_app,dec_app,azimuth_norot,elevation_norot,vel_init_norot,vel_avg_norot,begin_latitude,begin_longitude,begin_height,end_latitude,end_longitude,end_height,duration,convergence_angle,median_fit_err,station_list,ra_geo_err,dec_geo_err,lam_geo_err,bet_geo_err,vel_geo_err,lam_hel_err,bet_hel_err,vel_hel_err,a_err,e_err,i_err,omega_err,asc_node_err,pi_err,q_err,true_anomaly_err,mean_anomaly_err,Q_err,n_err,T_err,Tj_err,ra_app_err,dec_app_err,azimuth_norot_err,elevation_norot_err,vel_init_norot_err,vel_avg_norot_err,begin_latitude_err,begin_longitude_err,begin_height_err,end_latitude_err,end_longitude_err,end_height_err,beg_fov,end_fov,radiant_err,radiated_energy,mass,peak_abs_mag,peak_height,F,num_stations,height_ch,cos_elevation_norot,elevation_norot_rad,obs_ci_lower,obs_ci_upper,mean,obs_ci_lower1,obs_ci_upper1,obs_ci_lower3,obs_ci_upper3
1,Solution,20161105_073705A,pylig,2.457698e+06,2016-11-05T07:37:05.105721+00:00,-1,...,223.093105,78.091118,95.334449,-12.984042,96.454300,-36.302299,20.684091,345.022966,-31.943232,23.145581,0.707515,0.574465,36.301966,155.291525,43.095817,198.387342,0.301072,204.706876,249.241369,1.113957,1.656156,0.595119,7.842152,95.365573,-9.317753,159.082696,34.838140,23.576768,24.420382,43.560143,-81.147294,91.153844,43.622565,-81.180142,85.919668,0.419000,25.998125,0.002618,"[02F, 01F]",0.020992,0.124462,0.027545,0.124158,0.034860,0.114661,0.082456,0.025090,0.000653,0.001642,0.090856,0.073954,0.000004,0.073957,0.001421,0.073957,0.108653,0.000429,0.002299,0.000823,0.006249,0.019496,0.114051,0.040769,0.110689,0.030709,0.009051,0.000045,0.000024,0.011495,0.000047,0.000022,0.008193,True,True,0.126133,8.692784,4.164721e-06,3.036135,91.153844,0.000000,2,5.234176,0.820769,0.608040,-0.426931,22.988372,11.280720,5.340497,17.220944,-6.447148,29.008588
3,Solution,20161105_074144A,gural,2.457698e+06,2016-11-05T07:41:44.655924+00:00,-1,...,223.096349,79.035174,26.979423,51.813560,45.972212,37.560262,118.535179,28.058616,36.506398,121.460879,-0.068435,9.794422,70.680497,235.465172,223.097474,98.562646,0.601842,304.535822,NaN,-0.738711,55.054321,NaN,-75.308106,27.542578,52.008840,302.301396,55.259245,118.886177,37.473731,43.754163,-81.418835,132.120518,43.635312,-81.158761,95.998959,1.051949,11.346172,NaN,"[01F, 02F]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.056260,0.101257,7.774325,0.113308,0.252440,28.777575,True,True,NaN,4.191665,8.528343e-07,4.876760,128.110365,0.111018,2,36.121558,0.569864,0.964456,-1.433936,21.980477,10.273270,4.333273,16.213268,-7.453923,28.000464
4,Solution,20161105_074833A,pylig,2.457698e+06,2016-11-05T07:48:33.392311+00:00,-1,...,223.101093,80.993857,46.511972,-8.076333,41.516182,-24.495043,23.879416,348.973863,-14.670140,39.093850,3.395585,0.813357,17.903018,78.711668,43.105543,121.817211,0.633762,281.285230,353.452616,6.157408,0.157519,6.257092,2.426991,48.795318,-5.367657,219.299298,33.111425,26.150159,20.401599,43.540924,-81.120176,100.575870,43.619257,-81.032366,93.138820,0.638244,18.898474,0.001683,"[02F, 01F]",0.027261,0.066142,0.049472,0.055507,0.004591,0.033407,0.025029,0.011306,0.011694,0.000412,0.023054,0.114354,0.000004,0.114358,0.000773,0.114357,0.037777,0.022624,0.000797,0.032461,0.004657,0.024827,0.061996,0.013658,0.065708,0.004257,0.006165,0.000039,0.000027,0.011461,0.000016,0.000011,0.006007,True,True,0.071438,3.081091,2.114989e-06,4.831930,96.606660,0.533708,2,7.437050,0.837610,0.577903,-4.267087,19.147583,7.440248,1.500185,13.380311,-10.287141,25.167637

In [126]:
plt.figure(figsize=(30, 20)) 
os.mkdir('height_velocity_hexbin_0712')
for i in range (9):
    #i=5
    for k in range(8):
        plt.subplot(3,3,k+1)
        df_bin_elev_mag = df1[(df1['elevation_norot']>0+i*10) & (df1['elevation_norot']<10+i*10) & (df1['vel_avg_norot'] < 100) & (df1['peak_abs_mag'] > k) & (df1['peak_abs_mag'] < k+1)]
        #plt.scatter(df_bin_elev_mag['vel_avg_norot'],df_bin_elev_mag['height_ch'],s=1,c='red')
        if (df_bin_elev_mag.shape[0] == 0):
            continue
        y1=df_bin_elev_mag['obs_ci_upper']
        y2=df_bin_elev_mag['mean']
        y3=df_bin_elev_mag['obs_ci_lower']
        y4=df_bin_elev_mag['obs_ci_upper1']
        y5=df_bin_elev_mag['obs_ci_lower1']
        y6=df_bin_elev_mag['obs_ci_upper3']
        y7=df_bin_elev_mag['obs_ci_lower3']
        x1=df_bin_elev_mag['vel_avg_norot']
        lists = sorted(zip(*[x1, y1]))
        new_x1, new_y1 = list(zip(*lists))
        lists = sorted(zip(*[x1, y2]))
        new_x1, new_y2 = list(zip(*lists))
        lists = sorted(zip(*[x1, y3]))
        new_x1, new_y3 = list(zip(*lists))
        lists = sorted(zip(*[x1, y4]))
        new_x1, new_y4 = list(zip(*lists))
        lists = sorted(zip(*[x1, y5]))
        new_x1, new_y5 = list(zip(*lists))
        lists = sorted(zip(*[x1, y6]))
        new_x1, new_y6 = list(zip(*lists))
        lists = sorted(zip(*[x1, y7]))
        new_x1, new_y7 = list(zip(*lists))
        plt.hexbin(df_bin_elev_mag['vel_avg_norot'],df_bin_elev_mag['height_ch'],gridsize=(100,150),cmap="turbo")
        plt.plot(new_x1,new_y6,alpha=.3,label="3σ PI", linestyle="dashed", c="green")
        plt.plot(new_x1,new_y7,alpha=.3, linestyle="dashed", c="green")
        plt.plot(new_x1,new_y1,alpha=.3,label="2σ PI", linestyle="dashed", c="cyan")
        plt.plot(new_x1,new_y3,alpha=.3, linestyle="dashed",c="cyan")
        plt.plot(new_x1,new_y4,alpha=.3,label="1σ PI", linestyle="dashed", c="red")
        plt.plot(new_x1,new_y5,alpha=.3,linestyle="dashed", c="red")
        plt.plot(new_x1,new_y2,alpha=.6,label="predicted mean",linestyle="dashed",c="orange")
        #plt.fill_between(df_bin_elev_mag['vel_avg_norot'],df_bin_elev_mag['obs_ci_lower'], df_bin_elev_mag['obs_ci_upper'],alpha=0.1)
        plt.xlim(0,80)
        plt.ylim(-10,30)
        plt.ylabel('Height differential (km)',size="x-large")
        plt.xlabel('Average apparent velocity (km/s)',size="x-large")
        plt.legend(loc='best',markerscale=5)
        plt.title('Elevation = (' + str(i*10) + '°, ' + str(10+i*10)+'°), ' + 'Mag = ' + '(' + str(k)  +',' + str(k+1) + ')',size="x-large")
    
    plt.savefig('height_velocity_hexbin_0712/height_velocity_' + str(i) + '.jpg')
    plt.clf()

In [111]:
plt.figure(figsize=(30, 20)) 
os.mkdir('height_velocity_scatter_0707_f2')
for i in range (9):
    #i=5
    for k in range(8):
        plt.subplot(3,3,k+1)
        df_bin_elev_mag = df1[(df1['elevation_norot']>0+i*10) & (df1['elevation_norot']<10+i*10) & (df1['vel_avg_norot'] < 100) & (df1['peak_abs_mag'] > k) & (df1['peak_abs_mag'] < k+1)]
        #plt.scatter(df_bin_elev_mag['vel_avg_norot'],df_bin_elev_mag['height_ch'],s=1,c='red')
        if (df_bin_elev_mag.shape[0] == 0):
            continue
        loc = []
        means = []
        stdevs = []
        for j in range (26):
            df_section = df_bin_elev_mag[(df_bin_elev_mag['vel_avg_norot'] > 10 + j*2.5) & (df_bin_elev_mag['vel_avg_norot'] < 12.5 + j*2.5)]
            if (df_section.shape[0] > 5):
                mean = df_section['height_ch'].median()
                std = df_section['height_ch'].std()
                means.append(mean)
                stdevs.append(std)
                loc.append(11.25+j*2.5)
        y1=df_bin_elev_mag['mean']
        x1=df_bin_elev_mag['vel_avg_norot']
        lists = sorted(zip(*[x1, y1]))
        new_x1, new_y1 = list(zip(*lists))
        plt.plot(new_x1,new_y1,alpha=1,label="predicted mean",linestyle="dashed",c="orange")
        plt.errorbar(loc,means,yerr=stdevs,fmt='o')
        #plt.axhline(y=0,color="red")
        #plt.fill_between(df_bin_elev_mag['vel_avg_norot'],df_bin_elev_mag['obs_ci_lower'], df_bin_elev_mag['obs_ci_upper'],alpha=0.1)
        plt.xlim(0,80)
        plt.ylim(-10,30)
        plt.ylabel('Height differential (km)',size="x-large")
        #plt.ylabel('Observed - Theoretical height (km)',size="x-large")
        plt.xlabel('Average apparent velocity (km/s)',size="x-large")
        plt.legend(loc='best',markerscale=5)
        plt.title('Elevation = (' + str(i*10) + '°, ' + str(10+i*10)+'°), ' + 'Mag = ' + '(' + str(k)  +',' + str(k+1) + ')',size="x-large")
    
    plt.savefig('height_velocity_scatter_0707_f2/height_velocity_' + str(i) + '.jpg')
    plt.clf()

In [133]:
plt.figure(figsize=(30, 20)) 
os.mkdir('height_elevation_hexbin_0712')
for i in range (13):
    #i=4
    for k in range (8):
        plt.subplot(3,3,k+1)
        df_bin_vel_mag = df1[(df1['vel_avg_norot']>10+i*5) & (df1['vel_avg_norot']<15+i*5) & (df1['peak_abs_mag'] > k) & (df1['peak_abs_mag'] < k+1)]
        if (df_bin_vel_mag.shape[0] == 0):
            continue
        y1=df_bin_vel_mag['obs_ci_upper']
        y2=df_bin_vel_mag['mean']
        y3=df_bin_vel_mag['obs_ci_lower']
        y4=df_bin_vel_mag['obs_ci_upper1']
        y5=df_bin_vel_mag['obs_ci_lower1']
        y6=df_bin_vel_mag['obs_ci_upper3']
        y7=df_bin_vel_mag['obs_ci_lower3']
        x1=df_bin_vel_mag['cos_elevation_norot']
        lists = sorted(zip(*[x1, y1]))
        new_x1, new_y1 = list(zip(*lists))
        lists = sorted(zip(*[x1, y2]))
        new_x1, new_y2 = list(zip(*lists))
        lists = sorted(zip(*[x1, y3]))
        new_x1, new_y3 = list(zip(*lists))
        lists = sorted(zip(*[x1, y4]))
        new_x1, new_y4 = list(zip(*lists))
        lists = sorted(zip(*[x1, y5]))
        new_x1, new_y5 = list(zip(*lists))
        lists = sorted(zip(*[x1, y6]))
        new_x1, new_y6 = list(zip(*lists))
        lists = sorted(zip(*[x1, y7]))
        new_x1, new_y7 = list(zip(*lists))
        plt.hexbin(df_bin_vel_mag['cos_elevation_norot'],df_bin_vel_mag['height_ch'],gridsize=(150,150),cmap="turbo")
        plt.plot(new_x1,new_y6,alpha=.3,label="3σ PI", linestyle="dashed", c="green")
        plt.plot(new_x1,new_y7,alpha=.3, linestyle="dashed", c="green")
        plt.plot(new_x1,new_y1,alpha=.3,label="2σ PI", linestyle="dashed", c="cyan")
        plt.plot(new_x1,new_y3,alpha=.3, linestyle="dashed",c="cyan")
        plt.plot(new_x1,new_y4,alpha=.3,label="1σ PI", linestyle="dashed", c="red")
        plt.plot(new_x1,new_y5,alpha=.3,linestyle="dashed", c="red")
        plt.plot(new_x1,new_y2,alpha=.6,label="predicted mean",linestyle="dashed",c="orange")
        plt.xlim(0,1)
        plt.ylim(-20,50)
        plt.ylabel('Height differential (km)',size="large")
        plt.xlabel('Elevation (°)',size="large")
        plt.legend(loc='best',markerscale=5)
        plt.title('Velocity = (' + str(10+i*5) + ' km/s, ' + str(15+i*5)+' km/s)' + ', Mag = ' + '(' + str(k)  +',' + str(k+1) + ')',size="x-large")
    
    plt.savefig('height_elevation_hexbin_0712/height_elevation_' + str(i) + '.jpg')
    plt.clf()

In [113]:
plt.figure(figsize=(30, 20))
os.mkdir('height_elevation_scatter_0707_f2')
for i in range (13):
    #i=4
    for k in range (8):
        plt.subplot(3,3,k+1)
        df_bin_vel_mag = df1[(df1['vel_avg_norot']>10+i*5) & (df1['vel_avg_norot']<15+i*5) & (df1['peak_abs_mag'] > k) & (df1['peak_abs_mag'] < k+1)]
        if (df_bin_vel_mag.shape[0] == 0):
            continue
        loc = []
        means = []
        stdevs = []
        for j in range (20):
            df_section = df_bin_vel_mag[(df_bin_vel_mag['cos_elevation_norot'] > 0 + j*0.05) & (df_bin_vel_mag['cos_elevation_norot'] < 0.05 + j*0.05)]
            if (df_section.shape[0] > 5):
                mean = df_section['height_ch'].median()
                std = df_section['height_ch'].std()
                means.append(mean)
                stdevs.append(std)
                loc.append(0.025+j*0.05)
        y1=df_bin_vel_mag['mean']
        x1=df_bin_vel_mag['cos_elevation_norot']
        lists = sorted(zip(*[x1, y1]))
        new_x1, new_y1 = list(zip(*lists))
        plt.plot(new_x1,new_y1,alpha=1,label="predicted mean",linestyle="dashed",c="orange")
        plt.errorbar(loc,means,yerr=stdevs,fmt='o')
        #plt.axhline(y=0,color="red")
        plt.xlim(0,1)
        plt.ylim(-20,50)
        plt.ylabel('Height differential (km)',size="large")
        #plt.ylabel('Observed - Theoretical height (km)',size="x-large")
        plt.xlabel('Cos elevation',size="large")
        plt.legend(loc='best',markerscale=5)
        plt.title('Velocity = (' + str(10+i*5) + ' km/s, ' + str(15+i*5)+' km/s)' + ', Mag = ' + '(' + str(k)  +',' + str(k+1) + ')',size="x-large")
    
    plt.savefig('height_elevation_scatter_0707_f2/height_elevation_' + str(i) + '.jpg')
    plt.clf()

In [134]:
plt.figure(figsize=(25, 30)) 
os.mkdir('height_magnitude_hexbin_0712')
for i in range(9):
    #i=6
    for k in range(13):
        plt.subplot(5,3,k+1)
        df_bin_elev_vel = df1[(df1['elevation_norot']>0+i*10) & (df1['elevation_norot']<10+i*10) & (df1['vel_avg_norot']>10+k*5) & (df1['vel_avg_norot']<15+k*5)]
        #plt.scatter(df_bin_elev_mag['vel_avg_norot'],df_bin_elev_mag['height_ch'],s=1,c='red')
        if (df_bin_elev_vel.shape[0] == 0):
            continue
        y1=df_bin_elev_vel['obs_ci_upper']
        y2=df_bin_elev_vel['mean']
        y3=df_bin_elev_vel['obs_ci_lower']
        y4=df_bin_elev_vel['obs_ci_upper1']
        y5=df_bin_elev_vel['obs_ci_lower1']
        y6=df_bin_elev_vel['obs_ci_upper3']
        y7=df_bin_elev_vel['obs_ci_lower3']
        x1=df_bin_elev_vel['peak_abs_mag']
        lists = sorted(zip(*[x1, y1]))
        new_x1, new_y1 = list(zip(*lists))
        lists = sorted(zip(*[x1, y2]))
        new_x1, new_y2 = list(zip(*lists))
        lists = sorted(zip(*[x1, y3]))
        new_x1, new_y3 = list(zip(*lists))
        lists = sorted(zip(*[x1, y4]))
        new_x1, new_y4 = list(zip(*lists))
        lists = sorted(zip(*[x1, y5]))
        new_x1, new_y5 = list(zip(*lists))
        lists = sorted(zip(*[x1, y6]))
        new_x1, new_y6 = list(zip(*lists))
        lists = sorted(zip(*[x1, y7]))
        new_x1, new_y7 = list(zip(*lists))
        plt.hexbin(df_bin_elev_vel['peak_abs_mag'],df_bin_elev_vel['height_ch'],gridsize=(100,150),cmap="turbo")
        plt.plot(new_x1,new_y6,alpha=.3,label="3σ PI", linestyle="dashed", c="green")
        plt.plot(new_x1,new_y7,alpha=.3, linestyle="dashed", c="green")
        plt.plot(new_x1,new_y1,alpha=.3,label="2σ PI", linestyle="dashed", c="cyan")
        plt.plot(new_x1,new_y3,alpha=.3, linestyle="dashed",c="cyan")
        plt.plot(new_x1,new_y4,alpha=.3,label="1σ PI", linestyle="dashed", c="red")
        plt.plot(new_x1,new_y5,alpha=.3,linestyle="dashed", c="red")
        plt.plot(new_x1,new_y2,alpha=.6,label="predicted mean",linestyle="dashed",c="orange")
        #plt.fill_between(df_bin_elev_mag['vel_avg_norot'],df_bin_elev_mag['obs_ci_lower'], df_bin_elev_mag['obs_ci_upper'],alpha=0.1)
        plt.xlim(0,7)
        plt.ylim(-10,30)
        plt.gca().invert_xaxis()
        plt.ylabel('Height differential (km)',size="x-large")
        plt.xlabel('Peak absolute magnitude',size="x-large")
        plt.legend(loc='best',markerscale=5)
        plt.title('Elevation = (' + str(i*10) + '°, ' + str(10+i*10)+'°), ' + 'Velocity = (' + str(10+k*5) + ' km/s, ' + str(15+k*5)+' km/s)',size="x-large")
    
    plt.savefig('height_magnitude_hexbin_0712/height_magnitude_' + str(i) + '.jpg')
    plt.clf()

In [124]:
plt.figure(figsize=(25, 30)) 
os.mkdir('height_magnitude_0707')
for i in range(9):
    #i=3
    for k in range(13):
        plt.subplot(5,3,k+1)
        df_bin_elev_vel = df1[(df1['elevation_norot']>0+i*10) & (df1['elevation_norot']<10+i*10) & (df1['vel_avg_norot']>10+k*5) & (df1['vel_avg_norot']<15+k*5)]
        #plt.scatter(df_bin_elev_mag['vel_avg_norot'],df_bin_elev_mag['height_ch'],s=1,c='red')
        if (df_bin_elev_vel.shape[0] == 0):
            continue
        loc = []
        means = []
        stdevs = []
        for j in range (14):
            df_section = df_bin_elev_vel[(df_bin_elev_vel['peak_abs_mag'] > 0 + j*0.5) & (df_bin_elev_vel['peak_abs_mag'] < 0.5 + j*0.5)]
            if (df_section.shape[0] > 5):
                mean = df_section['height_ch'].median()
                std = df_section['height_ch'].std()
                means.append(mean)
                stdevs.append(std)
                loc.append(0.25+j*0.5)
        y1=df_bin_elev_vel['mean']
        x1=df_bin_elev_vel['peak_abs_mag']
        lists = sorted(zip(*[x1, y1]))
        new_x1, new_y1 = list(zip(*lists))
        plt.plot(new_x1,new_y1,alpha=1,label="predicted mean",linestyle="dashed",c="orange")
        plt.errorbar(loc,means,yerr=stdevs,fmt='o')
        #plt.hexbin(df_bin_elev_vel['peak_abs_mag'],df_bin_elev_vel['abs_height_diff'],gridsize=(100,150),cmap="turbo")
        #plt.axhline(y=0,color="red")
        #plt.fill_between(df_bin_elev_mag['vel_avg_norot'],df_bin_elev_mag['obs_ci_lower'], df_bin_elev_mag['obs_ci_upper'],alpha=0.1)
        plt.xlim(0,7)
        plt.ylim(-10,30)
        plt.gca().invert_xaxis()
        plt.ylabel('Height differential (km)',size="x-large")
        #plt.ylabel('Observed - Theoretical height (km)',size="x-large")
        plt.xlabel('Peak absolute magnitude',size="x-large")
        plt.legend(loc='best',markerscale=5)
        plt.title('Elevation = (' + str(i*10) + '°, ' + str(10+i*10)+'°), ' + 'Velocity = (' + str(10+k*5) + ' km/s, ' + str(15+k*5)+' km/s)',size="x-large")
    
    plt.savefig('height_magnitude_0707/height_magnitude_' + str(i) + '.jpg')
    plt.clf()